### ISSUE TITLE
1.19.3 - NoSuchMethodError on startup

### ISSUE THREAD

**Issue by Harvle** [mschae23/grind-enchantments#33]
When trying to load this mod in 1.19.3, the following error shows on startup:

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'grindenchantments'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:465)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.class_2370.<init>(net.minecraft.class_5321, com.mojang.serialization.Lifecycle, java.util.function.Function)'
	at de.martenschaefer.grindenchantments.util.FabricRegistryBuilderUtil.createSimple(FabricRegistryBuilderUtil.java:24)
	at de.martenschaefer.grindenchantments.registry.GrindEnchantmentsRegistries.<clinit>(GrindEnchantmentsRegistries.java:9)
	at de.martenschaefer.grindenchantments.cost.CostFunction.<clinit>(CostFunction.java:10)
	at de.martenschaefer.grindenchantments.config.DisenchantConfig.lambda$static$0(DisenchantConfig.java:12)
	at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72)
	at de.martenschaefer.grindenchantments.config.DisenchantConfig.<clinit>(DisenchantConfig.java:10)
	at de.martenschaefer.grindenchantments.config.GrindEnchantmentsConfig.lambda$static$0(GrindEnchantmentsConfig.java:8)
	at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72)
	at de.martenschaefer.grindenchantments.config.GrindEnchantmentsConfig.<clinit>(GrindEnchantmentsConfig.java:8)
	at de.martenschaefer.grindenchantments.GrindEnchantmentsMod.<clinit>(GrindEnchantmentsMod.java:45)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
```

**Comment by JosephTheMan** [comment]
I'm having this problem too.

**Comment by mschae23** [comment]
I have now uploaded version 2.0.0+1.19.3, which fixes this.
