### ISSUE TITLE
Already compatible with 1.19.4

### ISSUE THREAD

**Issue by M8torr** [mschae23/grind-enchantments#42]
Seems grind-enchantments-3.0.0-beta.1+1.19.3.jar is already compatible with 1.19.4.
Could you please mark it as compatible in Modrinth?

Thanks

**Comment by M8torr** [comment]
Seems it works without issues on Single Player, but on server it throws this error on 1.19.4
```
[07:15:36] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'grindenchantments'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.17.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-launch.jar:0.11.2]
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.class_2370.<init>(net.minecraft.class_5321, com.mojang.serialization.Lifecycle, java.util.function.Function)'
	at de.martenschaefer.grindenchantments.util.FabricRegistryBuilderUtil.createSimple(FabricRegistryBuilderUtil.java:24) ~[grind-enchantments-3.0.0-beta.1+1.19.2.jar:?]
	at de.martenschaefer.grindenchantments.registry.GrindEnchantmentsRegistries.<clinit>(GrindEnchantmentsRegistries.java:9) ~[grind-enchantments-3.0.0-beta.1+1.19.2.jar:?]
	at de.martenschaefer.grindenchantments.cost.CostFunction.<clinit>(CostFunction.java:10) ~[grind-enchantments-3.0.0-beta.1+1.19.2.jar:?]
	at de.martenschaefer.grindenchantments.config.DisenchantConfig.lambda$static$0(DisenchantConfig.java:12) ~[grind-enchantments-3.0.0-beta.1+1.19.2.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72) ~[datafixerupper-6.0.6.jar:?]
	at de.martenschaefer.grindenchantments.config.DisenchantConfig.<clinit>(DisenchantConfig.java:10) ~[grind-enchantments-3.0.0-beta.1+1.19.2.jar:?]
	at de.martenschaefer.grindenchantments.config.GrindEnchantmentsV2Config.lambda$static$0(GrindEnchantmentsV2Config.java:9) ~[grind-enchantments-3.0.0-beta.1+1.19.2.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72) ~[datafixerupper-6.0.6.jar:?]
	at de.martenschaefer.grindenchantments.config.GrindEnchantmentsV2Config.<clinit>(GrindEnchantmentsV2Config.java:9) ~[grind-enchantments-3.0.0-beta.1+1.19.2.jar:?]
	at de.martenschaefer.grindenchantments.GrindEnchantmentsMod.<clinit>(GrindEnchantmentsMod.java:31) ~[grind-enchantments-3.0.0-beta.1+1.19.2.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.17.jar:?]
```

**Comment by XBlayz** [comment]
I have tried it on my server and seems to work fine.

I'm using the `0.11.2 Fabric-loader` (MC 1.19.4) with the `3.0.0-beta 1-19.3` version of the mod.

**Comment by mschae23** [comment]
Sorry, I forgot about this! I'll fix this tomorrow.

**Comment by mschae23** [comment]
I've now released 3.0.0+1.19.4 on Modrinth and CurseForge, which is compatible with 1.19.4.
Let me know if you have any issues!
